name = "cloudflare"
main = "src/index.ts"
compatibility_date = "2023-01-01"
kv_namespaces = [
  { binding = "DB", id = "f27a02064f8f4f3eb2c284958e4a9f16" }
]

# [vars]

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""
