name = "cloudflare"
main = "src/app.ts"
compatibility_date = "2023-01-01"
kv_namespaces = [
  { binding = "DB", id = "f27a02064f8f4f3eb2c284958e4a9f16" }
]

[env.staging]
name = "my-worker-staging"
kv_namespaces = [
  { binding = "DB", id = "f27a02064f8f4f3eb2c284958e4a9f16" }
]
